# Generated by Django 2.0.6 on 2020-04-16 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(max_length=32, unique=True)),
                ('company_id', models.CharField(db_index=True, default='', max_length=32)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('english_name', models.CharField(db_index=True, default='', max_length=64)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('profile_photo', models.ImageField(default='clubstatic/img/athlete/default-photo.png', max_length=128, upload_to='clubstatic/img/athlete')),
                ('nationality', models.CharField(default='', max_length=32)),
                ('native_place', models.CharField(default='', max_length=255)),
                ('folk', models.CharField(default='汉族', max_length=32)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('sport_project', models.CharField(max_length=32)),
                ('hand_held', models.IntegerField(choices=[(0, '右手'), (1, '左手')], default=0)),
                ('sport_level', models.IntegerField(choices=[(0, '特级'), (1, '一级'), (2, '二级'), (3, '三级'), (4, '四级'), (5, '五级'), (6, '六级'), (7, '七级'), (8, '八级')])),
                ('initial_training_time', models.DateTimeField(blank=True, null=True)),
                ('first_coach', models.CharField(default='', max_length=64)),
                ('pro_team_coach', models.CharField(default='', max_length=64)),
                ('nat_team_coach', models.CharField(default='', max_length=64)),
                ('state', models.IntegerField(choices=[(0, '启用'), (1, '删除'), (2, '禁用')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'athlete_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=32, unique=True)),
                ('level1', models.CharField(default='', max_length=32)),
                ('level2', models.CharField(default='', max_length=32)),
                ('match_type', models.IntegerField(choices=[(0, '男单'), (1, '女单'), (2, '男双'), (3, '女双'), (4, '混双')], default=0)),
                ('match_name', models.CharField(db_index=True, max_length=128)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('player_a', models.CharField(db_index=True, max_length=32)),
                ('player_a_id', models.CharField(db_index=True, max_length=128)),
                ('player_b', models.CharField(db_index=True, max_length=32)),
                ('player_b_id', models.CharField(db_index=True, max_length=128)),
                ('winnum_a', models.IntegerField(default=0)),
                ('winnum_b', models.IntegerField(default=0)),
                ('match_result', models.IntegerField(choices=[(1, '胜'), (2, '负')])),
                ('match_round', models.CharField(default='', max_length=32)),
                ('memo', models.CharField(default='', max_length=2048)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_info',
                'managed': False,
            },
        ),
    ]
